Repository DeveloperAcademy-POSTECH/MacC-Team-NoPower, pull requests merged in 2022-11, with the labels that each got.

#146 [Fix] 회원가입하지 않으면 체크아웃 뜨는 버그 수정
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Fix

#144 [Feat] #143 런치스크린 완성 및 이미지 업데이트
  BNomad/Application/Assets.xcassets/BNOMADLGO.imageset/BNOMADLGO.png
  BNomad/Application/Assets.xcassets/BNOMADLGO.imageset/Contents.json
  BNomad/Application/Base.lproj/LaunchScreen.storyboard
Labels: Feature

#145 [Fix] 프로필뷰, 캘린더뷰 오토레이아웃 수정
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
Labels: Fix

#148 [Bug] #147 네비게이션 버그를 삭제합니다
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/SceneDelegate.swift
  BNomad/Application/ViewController.swift
Labels: Bug

#149 [Feat] 체크인 상태에서 앱 새로 시작 시 맵 위치 초기화, 모달표시 기능 구현
  BNomad/Application/CombineViewModel.swift
  BNomad/View/MapView/MapViewController.swift
Labels: Feature

#151 [setting] firebase 라이브러리를 추가합니다
  BNomad.xcodeproj/project.pbxproj
Labels: Setting

#153 [Bug] iOS15 이하 버전 Annotation 노출 + 회원가입 텍스트필드 키보드return 구현
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Bug, Feature

#155 [Feat] signUp 시점 A/B 테스트 구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/SceneDelegate.swift
  BNomad/Utils/RCValue.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#154 [Fix]프로필뷰 오토레이아웃 수정 및 버그픽스
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
  BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Bug

#158 [Bug] '업무중' 실시간 반영, 클릭가능하게
  BNomad/View/MapView/MapViewController.swift
Labels: Bug

#157 [Feat] #150 PlaceViewBeforeCheckIn 피드백 반영해서 수정
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Feature

#162 [Feat]PlaceInfoCell UI변경
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
Labels: Feature

#163 [Feat] #159 MeetUpView UI 작업입니다.
  BNomad.xcodeproj/project.pbxproj
  BNomad/Utils/Extensions/UIColor+Extension.swift
  BNomad/View/MeetUpView/MeetUpViewController.swift
  BNomad/View/MeetUpView/ParticipantCell.swift
Labels: Feature

#170 [Feat] #161 CheckInListView header UI, 코드정리
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Feature

#172 [Feat] meetUp 모델 생성, 관련된 firebase api 구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/API/FirebaseManager.swift
  BNomad/API/FirebaseTestVC.swift
  BNomad/Model/MeetUp.swift
Labels: Feature

#181 [Feat] 캘린더 레이블 수정
  BNomad/Utils/Extensions/UIColor+Extension.swift
  BNomad/View/ProfileView/CalendarCell.swift
  BNomad/View/ProfileView/CalendarViewController.swift
Labels: Enhancement

#176 [Feat] #166 NewMeetUpView UI 작업 완료
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/MeetUpView/NewMeetUpViewController.swift
Labels: Feature

#177 [feat]OperatingTimeLable Expandable sizing 구현
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#186 [Feat] CheckInListProfile , Header UI 완성
  BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Feature

#184 [Feat] 지역 선택 기능 구현 및 신규 UI 변경
  BNomad.xcodeproj/project.pbxproj
  BNomad/Model/Place.swift
  BNomad/View/MapView/MapData.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MapView/RegionCollectionViewCell.swift
  BNomad/View/MapView/RegionSelectViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Feature

#185 [Feat] #178 SignUpView 수정
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Enhancement

#195 [Bug] 지역선택 버튼 버그 수정
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MapView/RegionCollectionViewCell.swift
  BNomad/View/MapView/RegionSelectViewController.swift
Labels: Bug

#196 [Feat] 비로그인 상태에서 로그인 뷰로 넘어가는 alert 구현
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#194 [Feat] UserReview Cell UI 구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/Assets.xcassets/ReviewPhoto.imageset/Contents.json
  BNomad/Application/Assets.xcassets/ReviewPhoto.imageset/ReviewPhoto.jpeg
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
  BNomad/View/PlaceInfoView/SummaryInfoCell.swift
Labels: Feature

#198 [Feat]캘린더 비짓카드뷰 구현 및 네비게이션 루트 변경
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Feature

#203 [Fix] 맵 버그 수정 완료
  BNomad/View/MapView/MapViewController.swift
Labels: Fix

#211 [Fix] 맵 안에 보이는 장소들만 골라서 리스트에 보내주기
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Enhancement, Fix

#209 [Feat] #208 3번째셀 구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/WithNomadCell/WithNomadHeader.swift
Labels: Feature

#206 [Fix] 캘린더뷰 비짓카드 다중생성 및 코드 리펙토링
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Enhancement

#204 [Feat] #189 체크인뷰와 밋업뷰, 밋업생성뷰 연결
  BNomad/Utils/Extensions/UIColor+Extension.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MeetUpView/MeetUpViewController.swift
  BNomad/View/MeetUpView/NewMeetUpViewController.swift
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#213 [Feat] suggest place
  BNomad/API/FirebaseManager.swift
  BNomad/View/SettingView/PlaceRequestViewController.swift
Labels: Feature

#216 [Feat] #210 애플로그인모달 UI완성
  BNomad/View/LoginView/LoginViewController.swift
Labels: Enhancement, Feature

#207 [Feat] #169 Review Detail View Controller UI 2nd sprint
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/Info.plist
  BNomad/View/ReviewView/ReviewDetailViewController.swift
Labels: Feature

#215 [Feat] firebase에 탈퇴 사유 업로드
  BNomad/API/FirebaseManager.swift
Labels: Feature

#217 [Feat] #168 ReviewListView UI 2nd sprint
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/ReviewView/ReviewCell.swift
  BNomad/View/ReviewView/ReviewListViewController.swift
  BNomad/View/ReviewView/ReviewViewController.swift
Labels: Feature

#219 [Feat] review 모델 생성 & firebase api & 데이터 바인딩
  BNomad.xcodeproj/project.pbxproj
  BNomad/API/FirebaseManager.swift
  BNomad/Model/Review.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
Labels: Feature

#220 [Feat] 프로필 이미지 수정하기
  BNomad/API/FirebaseManager.swift
  BNomad/Application/SceneDelegate.swift
  BNomad/Model/User.swift
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Feature

#221 [Integrate] #218 화면 연결과 최소한의 기능 추가
  BNomad/Application/Assets.xcassets/nomadlaunch.imageset/Contents.json
  BNomad/Application/Assets.xcassets/nomadlaunch.imageset/nomadlaunch.png
  BNomad/Application/Base.lproj/LaunchScreen.storyboard
  BNomad/View/LoginView/LoginViewController.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MeetUpView/MeetUpViewController.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
  BNomad/View/ProfileView/CalendarCell.swift
  BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
  BNomad/View/ReviewView/ReviewDetailViewController.swift
  BNomad/View/SettingView/PlaceRequestViewController.swift
Labels: Enhancement, Integrate

#227 [Feat]캘린더, 리스트 분기 및 리펙터링
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitCardCollectionViewController.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Feature, Chore

#228 [Feat] #226 PlaceCheckInView 체크인, 이용시간 프로그레스바 구현
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
Labels: Feature

#229 [Feat] 체크인 시 textfield 구현
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#237 [Feat] 프로필뷰 리펙터링(그래프 뷰컨->셀 이동) 및 비짓카드컬렉션뷰 헤더 생성
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitCardCollectionViewController.swift
  BNomad/View/ProfileView/VisitCardHeaderCollectionView.swift
Labels: Enhancement, Fix

#234 [Feat] 영업중 섹션 UI디자인 변경 적용
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
Labels: Feature

#239 [Feat] #224 애플로그인, UI작동, 로그인, 로그아웃, 회원탈퇴
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/SceneDelegate.swift
  BNomad/BNomad.entitlements
  BNomad/View/LoginView/LoginViewController.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/SettingView/SettingViewController.swift
  BNomad/View/SettingView/WithdrawViewController.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#241 [Enhancement] #236 SignUpView 업데이트
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Enhancement

#247 [Enhancement] 프로필뷰 전체 프로퍼티 컬렉션뷰로 리펙터링 / 초기 로그인 버그 픽스 / 외 다수 버그픽스
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
  BNomad/View/ProfileView/ProfileHeaderCollectionView.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitCardHeaderCollectionView.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Bug, Enhancement, Fix

#238 [Feat] 방문했던 장소만 모아보는 토글 구현 완료
  BNomad/View/MapView/MapData.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MapView/PlaceAnnotation.swift
Labels: Feature

#251 [Feat] 프로필 이미지 바인딩
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
Labels: Feature

#249 [Feat] #246 MeetUpView 밋업 프로필사진 둥글게, 참여중인 경우 참여 취소 버튼
  BNomad/API/FirebaseManager.swift
  BNomad/View/MeetUpView/MeetUpViewController.swift
  BNomad/View/MeetUpView/ParticipantCell.swift
  BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
Labels: Feature, Fix

#265 [Feat] #232 ReviewListViewController 에 Dynamic Cell Height 추가
  BNomad/Utils/Extensions/String+Extension.swift
  BNomad/View/ReviewView/ReviewCell.swift
  BNomad/View/ReviewView/ReviewListViewController.swift
Labels: Feature

#254 [Enhancement] #250 리뷰 데이터 바인딩 및 Firebase 업데이트
  BNomad/API/FirebaseManager.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/ReviewView/ReviewDetailViewController.swift
Labels: Enhancement, Feature

#260 [Feat] PlaceInfoModal View 내에 DynamicHeight 구현 및 UI 세부 조정
  BNomad/Utils/Extensions/UIColor+Extension.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
  BNomad/View/PlaceInfoView/WithNomadCell/WithNomadHeader.swift
Labels: Enhancement, Feature

#261 [Feat] 프로필뷰 UI수정, 오토레이아웃 및 버그 픽스
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
Labels: Bug, Enhancement

#266 [Enhancement] #264 CustomModalView UI 업데이트
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Enhancement

#262 [Feat] #231 밋업 편집 구현
  BNomad/API/FirebaseManager.swift
  BNomad/View/MeetUpView/MeetUpViewController.swift
  BNomad/View/MeetUpView/NewMeetUpViewController.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
Labels: Feature

#263 [Feat] #256 체크인뷰의 노마드들을 클릭하면 각자의 프로필뷰로 이동
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MeetUpView/ParticipantCell.swift
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Feature

#267 [Enhancement] #257 로그아웃, 회원탈퇴 Firebase 업데이트 구현, SettingView 네비게이션 오류 고침
  BNomad/API/FirebaseManager.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/SettingView/SettingViewController.swift
  BNomad/View/SettingView/WithdrawViewController.swift
Labels: Enhancement, Feature

#270 [Feat] 체크인 버튼 구현
  BNomad/View/MapView/MapViewController.swift
Labels: Feature

#272 [chore]1차 출시 이전 마지막 ui수정
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
Labels: Chore

#277 [FIX] 프로필뷰 스크롤 버그 픽스
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Bug

#280 [Enhancement] #271 CheckIn History fetch, logout
  BNomad/View/LoginView/LoginViewController.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Bug, Enhancement

#281 [Bug] #275 노마드 프로필 데이터 바인딩 수정
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Bug

#278 [Feat]프로필뷰 UI 수정 및 버그픽스
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileHeaderCollectionView.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitCardCell.swift
  BNomad/View/ProfileView/VisitCardCollectionViewController.swift
Labels: Enhancement

#283 [Fix] 체크인 카드 바인딩 & 체크인 후 장소 모달 내 버튼 변경
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Enhancement, Feature, Fix

#288 [Fix] launch screen UI update
  BNomad/Application/Assets.xcassets/nomadlaunch.imageset/Contents.json
  BNomad/Application/Assets.xcassets/nomadlaunch.imageset/nomadlaunch.png
Labels: Bug, Fix

#286 [Fix]프로필뷰 오토레이아웃 버그픽스, 캘린더뷰 선택 버그픽스, 카드 통일
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileHeaderCollectionView.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitCardCell.swift
Labels: Bug, Enhancement

#290 [Bug, Enhancement] #289 탈퇴이유 default 업로드 막음, 탈퇴시 Storage이미지 삭제
  BNomad/API/FirebaseManager.swift
  BNomad/View/SettingView/WithdrawViewController.swift
Labels: Bug, Enhancement

#292 [Bug] #291 user position 값으로 app crash되는 현상 Fix
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Bug

#299 [Feat] 영업시간 데이터 바인딩
  BNomad/API/FirebaseManager.swift
  BNomad/Model/Place.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
Labels: Feature

#294 [Feat] #293 PlaceCheckInView 밋업 없을 때 표시할 셀 추가
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceCheckInView/NoMeetUpCell.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
Labels: Feature

#302 [Feat] #295 PlaceCheckInView 함께 일하고 있는 노마드 목록에서 자기 자신 제외
  BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Enhancement

#307 [Enhancement] app icon update
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/100.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/1024.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/114.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/120.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/128.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/144.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/152.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/16.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/167.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/172.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/180.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/196.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/20.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/216.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/256.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/29.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/32.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/40.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/48.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/50.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/512.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/55.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/57.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/58.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/60.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/64.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/66.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/72.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/76.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/80.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/87.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/88.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/92.png
  BNomad/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Enhancement

#308 [Bug] PlaceInfoView 버그
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
  BNomad/View/PlaceInfoView/ReviewSubCell/ReviewSubCell.swift
Labels: Enhancement

#306 [Bug] 네비게이션바 색상 변경 해결 & 커스텀 모달 버그 해결
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Bug, Enhancement

#319 [Enhancement] 프로필뷰 UI 개선
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileGraphCollectionCell.swift
  BNomad/View/ProfileView/ProfileHeaderCollectionView.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
  BNomad/View/ProfileView/VisitCardCell.swift
  BNomad/View/ProfileView/VisitCardCollectionViewController.swift
  BNomad/View/ProfileView/VisitCardHeaderCollectionView.swift
Labels: Enhancement

#311 [Chore] NavBar 컬러 체인지
  BNomad/View/MapView/MapViewController.swift
Labels: Bug

#297 [Feat] #282 ReviewListView Data Binding
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/ReviewView/ReviewCell.swift
  BNomad/View/ReviewView/ReviewListViewController.swift
Labels: Feature

#315 [Enhancement] 핀 보기 방식 선택 버튼을 위한 에셋 추가
  BNomad/Application/Assets.xcassets/locationForButton.imageset/Contents.json
  BNomad/Application/Assets.xcassets/locationForButton.imageset/locationForButton.png
  BNomad/Application/Assets.xcassets/locationForButtonWhite.imageset/Contents.json
  BNomad/Application/Assets.xcassets/locationForButtonWhite.imageset/locationForButtonWhite.png
Labels: Enhancement

#309 [Enhancement] #304 로그인 로그아웃 toggle
  BNomad/View/SettingView/SettingViewController.swift
Labels: Enhancement

#312 [Bug] #310 셀 reuse되는 에러 fix
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Bug

#321 [Feat] #320 밋업 모임 시간 지나면 회색 & 선택 시 alert
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/PlaceCheckInView/QuestCollectionViewCell.swift
Labels: Feature

#324 [Feat] 자기소개 대신 오늘의 목표를 바인딩
  BNomad/API/FirebaseManager.swift
  BNomad/Model/CheckIn.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#318 [Bug] #303 밋업생성뷰, 장소제안뷰 키보드가 입력칸 가리는 문제 해결
  BNomad/View/MeetUpView/NewMeetUpViewController.swift
  BNomad/View/SettingView/PlaceRequestViewController.swift
  BNomad/View/SettingView/RequestTextField.swift
  BNomad/View/SettingView/SettingViewController.swift
Labels: Bug

#326 [Feat] #322 밋업 모집인원 다 차면 참여불가
  BNomad/View/MeetUpView/MeetUpViewController.swift
Labels: Feature

#328 [Bug] #327 체크인 버튼 crash 오류 수정 + ReviewListView 연결
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
  BNomad/View/ReviewView/ReviewListViewController.swift
Labels: Bug

#331 [Feat] 모달 사이즈 , 리뷰 전체보기 버튼 추가
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/ReviewInfoCell.swift
Labels: Feature, waiting for approval

#333 [Fix] 프로필 수정 버튼 버그 픽스
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
Labels: Bug

#330 [Feat] 파이어 베이스 캐시 처리
  BNomad/API/FirebaseManager.swift
  BNomad/Application/SceneDelegate.swift
Labels: Feature

#335 [Enhancement] Spot 아이콘 변경
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Enhancement

#336 [Feat] #329 지난 밋업 관련 수정
  BNomad/View/MeetUpView/MeetUpViewController.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/SettingView/SettingViewController.swift
Labels: Feature

#345 [Enhancement] #343 체크인된 장소 셀 UI 변경
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Enhancement

#339 [Bug] 버튼 비활성화 버그 해결
  BNomad/View/MapView/MapViewController.swift
Labels: Bug

#342 [Bug] #341 체크인뷰 오늘의 목표 데이터 바인딩 오류 수정
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Bug
