Repository DeveloperAcademy-POSTECH/MacC-Team-NoPower, pull requests merged in 2022-10, with the labels that each got.

#8 [Feat] 맵 기본 화면 구현 완료 (지도, 위치, 기본버튼)
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/MapView/MapViewController.swift
Labels: Feature

#10 [Feat] #3 PlaceInfoview Modal 구현
  BNomad/View/PlaceInfoView/PlaceInfoViewController.swift
Labels: Feature

#9 [Feat] 프로필뷰 첫 페이지 기초 UI
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/Assets.xcassets/ProfileDefault.imageset/Contents.json
  BNomad/Application/Assets.xcassets/ProfileDefault.imageset/Group 131.png
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Feature

#13 [Feat] #5 SignUpView UI 작업
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#18 [Feat] #14 프로필 통계뷰 UI / 추가 : 프로필 캘린더 뷰 UI
  BNomad.xcodeproj/project.pbxproj
  BNomad/Utils/LiteralContents.swift
  BNomad/View/ProfileView/CalendarCell.swift
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Feature

#17 [Feat] PlaceView before CheckIn UI
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/SceneDelegate.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/FinalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/ModalViewController.swift
  BNomad/View/PreCheckInPlaceView/PreCheckInPlaceViewController.swift
Labels: Feature

#22 [Feat] #19 Profile Editing View UI 작업
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/Info.plist
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
Labels: Feature

#21 [Feat] #12 모달뷰 내에 콜렉션뷰 구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceInfoView/DemoCell.swift
  BNomad/View/PlaceInfoView/DemoCell2.swift
  BNomad/View/PlaceInfoView/DemoCell3.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoViewController.swift
Labels: Feature

#25 [Feat] 캘린더뷰 달(Month) 넘어가는 로직 구현 + 날자 클릭시 보더 띄워주는 기능 구현
  BNomad/Utils/LiteralContents.swift
  BNomad/View/ProfileView/CalendarCell.swift
  BNomad/View/ProfileView/CalendarViewController.swift
Labels: Enhancement

#26 [Feat] PlaceCheckInView UI
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/Assets.xcassets/locationIcon.imageset/Contents.json
  BNomad/Application/Assets.xcassets/locationIcon.imageset/locationIcon.png
  BNomad/Application/Assets.xcassets/othersProfile.imageset/Contents.json
  BNomad/Application/Assets.xcassets/othersProfile.imageset/othersProfileImg.png
  BNomad/Application/Assets.xcassets/placeCheckInViewProfileLine.imageset/Contents.json
  BNomad/Application/Assets.xcassets/placeCheckInViewProfileLine.imageset/placeCheckInViewProfileLine.png
  BNomad/Application/Assets.xcassets/profileDefault.imageset/Contents.json
  BNomad/Application/Assets.xcassets/profileDefault.imageset/profile2.png
  BNomad/Application/Assets.xcassets/rectangleDivider.imageset/Contents.json
  BNomad/Application/Assets.xcassets/rectangleDivider.imageset/RectangleDivider.png
  BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/ColorViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/PlaceCheckInView/UserProfileViewCell.swift
Labels: Feature

#29 [Feat] #28 모달뷰 내에 UI구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/Assets.xcassets/Arrow.imageset/Contents.json
  BNomad/Application/Assets.xcassets/Arrow.imageset/arrow.png
  BNomad/Application/Assets.xcassets/Dot.imageset/Contents.json
  BNomad/Application/Assets.xcassets/Dot.imageset/Ellipse .png
  BNomad/Application/Assets.xcassets/Map.imageset/Contents.json
  BNomad/Application/Assets.xcassets/Map.imageset/map 1.png
  BNomad/Application/Assets.xcassets/Phone.imageset/Contents.json
  BNomad/Application/Assets.xcassets/Phone.imageset/phone.png
  BNomad/Application/Assets.xcassets/ProfileChecked.imageset/Contents.json
  BNomad/Application/Assets.xcassets/ProfileChecked.imageset/Group 88.png
  BNomad/Utils/Extensions/UIColor+Extension.swift
  BNomad/View/PlaceInfoView/DemoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoViewController.swift
Labels: Feature

#30 [Feat] 데이터 구조 변경
  BNomad.xcodeproj/project.pbxproj
  BNomad/Model/CheckIn.swift
  BNomad/Model/DummyData.swift
  BNomad/Model/Place.swift
  BNomad/Model/Position.swift
  BNomad/Model/User.swift
  BNomad/Model/UsersInPlace.swift
  BNomad/Utils/Extensions/Date+Extension.swift
  BNomad/Utils/Extensions/String+Extension.swift
Labels: Feature

#39 [IntegrateUI] 현재까지 작성된 UI를 합치고, action 추가, 코드 컨벤션을 맞췄습니다.
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/SceneDelegate.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/MapView/PlaceAnnotation.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/ColorViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/PlaceCheckInView/UserProfileViewCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/FinalViewController.swift
  BNomad/View/ProfileView/CalendarCell.swift
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
  BNomad/View/ProfileView/ProfileGraphCell.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/SelfUserInfoCell.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Integrate

#48 [Feat] #46 NewPlaceViewBeforeCheckIn UI
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Enhancement

#45 [Feat] View병합 이후 컴포넌트 위치, 셀, 모달 옵션 세부 조정 및 BasicInfoCell UI 구현
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceInfoView/BasicInfoCell.swift
  BNomad/View/PlaceInfoView/DemoCell3.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/PlaceInfoView/SummaryInfoCell.swift
Labels: Feature

#50 [Fix]프로필뷰, 캘린더뷰 버그 픽스
  BNomad/Application/Assets.xcassets/ProfileDefault.imageset/Contents.json
  BNomad/Application/Assets.xcassets/checkinStemp.imageset/Contents.json
  BNomad/Application/Assets.xcassets/checkinStemp.imageset/checkinMark.png
  BNomad/Application/Assets.xcassets/graph.imageset/Contents.json
  BNomad/Application/Assets.xcassets/graph.imageset/graph.png
  BNomad/Model/DummyData.swift
  BNomad/Utils/LiteralContents.swift
  BNomad/View/ProfileView/CalendarCell.swift
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Bug

#56 [Feat] #47 PlaceCheckInView 상단의 수정된 체크인 카드 UI 작업
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Feature

#57 [Chore] #55 Custom 모달파일 정리, 안쓰는 파일 정리
  BNomad.xcodeproj/project.pbxproj
  BNomad/Application/SceneDelegate.swift
  BNomad/Application/ViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/FinalViewController.swift
  BNomad/View/PlaceViewBeforeCheckIn/ModalViewController.swift
Labels: Chore, Setting

#54 [Feat] firebase CRUD 함수 작성
  BNomad.xcodeproj/project.pbxproj
  BNomad/API/FirebaseManager.swift
  BNomad/API/FirebaseTestVC.swift
  BNomad/Model/CheckIn.swift
  BNomad/Model/DummyData.swift
  BNomad/Model/User.swift
  BNomad/Utils/Extensions/Date+Extension.swift
  BNomad/Utils/Extensions/String+Extension.swift
Labels: Feature

#58 [Setting] #49 sign in apple 삭제
  BNomad/BNomad.entitlements
Labels: Setting

#60 [Feat] 현재위치 기준 반경 500미터 이내 확인하여 alert 메시지 분기 처리 완료
  BNomad/Application/Assets.xcassets/ProfileDefault.imageset/Contents.json
  BNomad/Application/Assets.xcassets/checkinStemp.imageset/Contents.json
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#68 [Feat] #63 SignUpView 글자수 제한 추가, 입력값 firebase 저장
  BNomad.xcodeproj/project.pbxproj
  BNomad/Utils/Extensions/UIViewController+Extension.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#71 [Feat] 로그인 판단 & 체크인 view 분기 & user 데이터 가져오기
  BNomad.xcodeproj/project.pbxproj
  BNomad/API/FirebaseManager.swift
  BNomad/Application/CombineViewModel.swift
  BNomad/Application/SceneDelegate.swift
  BNomad/Application/ViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#72 [Feat] Firebase 장소데이터 연결 및 뷰 간 데이터 전달 구현
  BNomad/View/MapView/MapData.swift
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/BasicInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#73 [Feat] #67 PlaceViewBeforeCheckIn 에서의 데이터 연결
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Feature

#74 [Feat] #62 PlaceCheckInView 데이터 연결
  BNomad/Model/DummyData.swift
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/PlaceInfoViewCell.swift
  BNomad/View/PlaceCheckInView/UserProfileViewCell.swift
Labels: Feature

#80 [Feat] #69 PlaceCheckInView 하단의 함께 일하고 있는 이용자 리스트 데이터 연결
  BNomad/Application/Assets.xcassets/profileDefault.imageset/Contents.json
  BNomad/Utils/Extensions/UILabel+Extension.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListHeader.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Feature

#76 [Feat] #75 체크인 이후의 타이머 UI와 기능을 완성했습니다.
  BNomad/Application/AppDelegate.swift
  BNomad/View/MapView/MapViewController.swift
Labels: Feature

#79 Feat/#65 map view place info view data binding
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/PlaceInfoView/BasicInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#92 [Feat] isLogin 상태 확인 후 뷰 분기
  BNomad/Application/Assets.xcassets/checkinStemp.imageset/Contents.json
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#95 [Feat] SignUpView 나가기 버튼 추가
  BNomad/View/SignUpView/SignUpViewController.swift
Labels: Feature

#100 [feat] checkIn, checkOut 함수 구현
  BNomad/Application/ViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Feature

#102 [bug] 모달 디스미스 버그 수정
  BNomad/View/MapView/MapViewController.swift
Labels: Bug

#101 [Feat] #87 CustomModalView에 체크인 인원, 평균시간, 거리 불러와서 띄우기
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomModalViewController.swift
Labels: Feature

#94 [Feat] 프로필 에딧 뷰 파베 연결
  BNomad/Application/Assets.xcassets/ProfileDefault.imageset/Contents.json
  BNomad/View/MapView/MapViewController.swift
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Enhancement

#111 [Fix]내비게이션 버그 픽스
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Bug

#116 Feat/#65 map view place info view data binding
  BNomad/View/MapView/MapViewController.swift
Labels: Bug

#117 [Feat] #107 맵뷰에서 선택된 장소로 데이터 연결
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Fix

#113 [Fix] #105 함께 일하는 노마더 명수 수정
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Fix

#112 [Feat] #106 PlaceInfoModalViewController 에 평균 근무 시간과 현재 체크인 된 사람 수 데이터 연결
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
Labels: Feature

#118 [Feat] #109 체크인, 체크아웃!
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Fix

#123 [Fix] #122 평균 근무 시간이 1시간 이내일 경우 0시간 몇분으로 뜨는 것을 막기 위해 calculateAverageTime 함수 조정
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
Labels: Fix

#128 [Fix&Chore] 상단 타이틀 원복 및 필요없는 코드 정리
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceCheckInView/ColorViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceCheckInView/UserProfileViewCell.swift
Labels: Chore, Fix

#127 [Fix] #126 평균 근무 시간이 이상하게 뜨는 것을 방지하기 위해 calculateAverageTime 함수 조정
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
Labels: Fix

#129 [Fix] 현재 체크인 명수 수정
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
  BNomad/View/PlaceInfoView/PlaceInfoCell.swift
  BNomad/View/PlaceViewBeforeCheckIn/CustomCollectionViewCell.swift
Labels: Fix

#131 [Fix] #120 UILabel 글자수 길어질 때 튀어나가지 않도록 함
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/CheckedProfileListViewCell.swift
Labels: Fix

#135 [chore]MapViewPlaceInfoView 코드 정리 및 표출되는 메세지 수정
  BNomad/View/PlaceInfoView/PlaceInfoModalViewController.swift
Labels: Chore

#138 [Fix] 프로필뷰 및 프로필수정뷰 사소한 수정
  BNomad/View/ProfileView/ProfileEditView/ProfileEditViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
Labels: Fix

#139 [Fix] 프로필뷰, 캘린더뷰 비짓카드셀 분기 설정 / 쉐브론 설정
  BNomad/View/ProfileView/CalendarViewController.swift
  BNomad/View/ProfileView/ProfileViewController.swift
  BNomad/View/ProfileView/VisitingInfoCell.swift
Labels: Bug, Enhancement

#140 [Feat] ListCellView에서 checkOut관련 로직을 만들었습니다 + iOS 최저 15로 버전 통일
  BNomad.xcodeproj/project.pbxproj
  BNomad/View/PlaceCheckInView/CheckInCardViewCell.swift
  BNomad/View/PlaceCheckInView/PlaceCheckInViewController.swift
Labels: Feature, Setting

#141 [Feat] 앱 시작 시 현재 위치 중심으로 시작
  BNomad/View/MapView/MapViewController.swift
Labels: Feature
